'use client'
import React from 'react'
import Typography from '../shared/typography'
import Link from 'next/link'
import { MoveLeft } from 'lucide-react'

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"

type SiteMapItem = {
  id: string;
  url: string;
  no_images: string;
  last_modified: string;
};

function PageSitemap({ sites_maps }: { sites_maps: SiteMapItem[] }) {
  return (
    <div className='w-full flex flex-col gap-6'>
        <section className='w-full py-10 bg-app-primary-medium'>
            <div className='max-container 2xl:w-[85%] md:w-[95%] w-[90%] mx-auto flex flex-col gap-6 text-white'>
                <Typography
                    typo="header-4-medium"
                >XML Sitemap</Typography>
                <div className='w-full flex flex-col gap-1'>
                    <Typography
                        typo="body-medium-light"
                    >
                        This XML Sitemap is generated by <span className='font-medium'>Rank Math WordPress SEO Plugin.</span> It is what search engines like Google use to crawl and re-crawl posts/pages/products/images/archives on your website. Learn more about XML Sitemaps.
                    </Typography>
                </div>
            </div>
        </section>
        <section className='w-full md:py-8 py-3'>
            <div className='max-container 2xl:w-[85%] md:w-[95%] w-[90%] mx-auto '>
                <div className='xl:w-[85%] mx-auto flex flex-col gap-3'>
                    <div className='flex flex-col md:gap-4 gap-2'>
                        <Typography
                            typo="body-medium-regular"
                        >This XML Sitemap contains 18 URLs.</Typography>
                        <Link href={process.env.NEXT_PUBLIC_MAIN_SITE_URL || "https://codersclutch.com"} className='flex items-center gap-2 text-app-primary-deep hover:text-blue-700'>
                            <MoveLeft size={14} />
                            <span className='text-sm'>Sitemap Index</span>
                        </Link>
                    </div>

                    <div className='w-full py-5 inter overflow-auto'>
                        <Table className='min-w-[1000px]'>
                            <TableHeader className=' text-white bg-app-primary-medium hover:bg-app-primary-deep'>
                                <TableRow className='p-4'>
                                    <TableHead className="px-6 py-4 w-[60%] text-base text-white font-semibold">URL</TableHead>
                                    <TableHead className='text-white  text-base font-semibold'>Image</TableHead>
                                    <TableHead className=" px-6  text-base text-white font-semibold">Last Mod.</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {sites_maps.map((data, index) => (
                                <TableRow key={data.id} className={`${index % 2 === 0 ? 'bg-white' : 'bg-gray-100'} `}>
                                    <TableCell className="w-[60%] px-6 py-3 font-light"> 
                                        <Link 
                                            href={data.url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                        >{data.url}</Link> 
                                    </TableCell>
                                    <TableCell className='font-light'>{data.no_images}</TableCell>
                                    <TableCell className="px-6 font-light">{data.last_modified}</TableCell>
                                </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                </div>
            </div>
        </section>
    </div>
  )
}

export default PageSitemap